### ISSUE TITLE
./uv4l-socket.sh: Permission denied

### ISSUE THREAD

**Issue by virtualdvid** [webrtcHacks/aiy_vision_web_server#6]
I'm following all the steps presented in the readme file and when I executed this command step 7 `sudo python3 setup.py install` I'm getting this:

```
Using /usr/lib/python3/dist-packages
Finished processing dependencies for aiy-vision-web-server==0.1
Disabling uv4l-raspidisp keyboard to socket and releasing /tmp/uv4l-raspidisp.socket
/bin/sh: 1: ./uv4l-socket.sh: Permission denied
```
Then in step 9, I executed `sudo python3 server.py` and I got the http://raspberrypi.local:5000. 

```
socket waiting for connection...
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
face model loaded
```
There I'm replacing the 0.0.0.0:5000 with my local raspberry pi IP and I'm not getting any image from my AIY but in the terminal is showing me when it recognizes my face.

What am I missing?

Thank you!

**Comment by chadwallacehart** [comment]
It sounds like 2 separate issues:
1. The `setup.py install` giving an error - I do not think that is actually causing any real issue since the webserver started fine
2. UV4l not sending any video 

on the 2nd issue:
Do you see the square annotation around your face in the browser window?

Can you share the contents of the console log of the browser you are using? We'll need to see why it isn't connecting.

Please also try going to http://raspberrypi.local:9080/stream/webrtc - click on the enable hardware checkbox and then place a call - you should see the Raspberry Pi desktop and if you start the aiy_web_server you should see the camera output.

**Comment by virtualdvid** [comment]
Hi, I did what you recommended and it worked. I don't know why the first try it doesn't work but once I reboot the raspberrypi and try it again it works... I'm going to test a different model instead of face recognition.

Thank you!!!

**Comment by chadwallacehart** [comment]
I noticed when I played around with mine last weekend I sometimes had to refresh my browser once or twice before it connected. I need to look into any potential uv4l signaling issues.

**Comment by chadwallacehart** [comment]
uv4l has had some signaling updates over the past couple of months. My latest update should address any issues and result in a much faster time to connect.

**Comment by Gh0stWires** [comment]
I'm getting the same thing. I just get a blank webpage when I run the server. I tried your suggestion above only when I try to click call I get this:
   "Sorry, the device is either busy streaming to another peer or previous shutdown has not been 
   completed yet"

**Comment by chadwallacehart** [comment]
UV4L takes a few seconds to close out its connection after you exit the page. If you hit "refresh" while there is an open connection it will almost always say "Sorry, the device is either busy streaming to another peer or previous shutdown has not been completed yet". If you hit refresh again it should connect.

I am noticing an issue where the remote video stream is not attaching the local `<video>` element. I need to look into this.

**Comment by chadwallacehart** [comment]
updated the repo to fix video autoplay.
